import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,dispatch,restore,objects,unlocked,dialog,objective} from '../js/engine.js';
import {ROOMS,ITEMS,HOTSPOT_COUNT,FRAGMENTS} from '../js/content.js';
import {route,event} from './route.mjs';
function play(steps=route,s=initialState()){for(const e of steps){s=dispatch(s,event(e)).state;invariants(s);}return s;}
function invariants(s){assert.equal(new Set(s.inventory).size,s.inventory.length);assert(s.inventory.every(i=>ITEMS[i]));assert(s.slots.every(i=>FRAGMENTS.includes(i)));assert.equal(new Set(s.slots).size,s.slots.length);assert(unlocked(s,s.room));assert(restore(JSON.stringify(s)));}
const before=marker=>play(route.slice(0,route.findIndex(x=>JSON.stringify(x)===JSON.stringify(marker))));
test('full command-driven route wins with all five characters and four fragments',()=>{const s=play();assert.equal(s.ending,'good');assert(s.flags.won);for(const f of ['andre','olli','felix','benny','origin','voice','clarity','found','team','publish'])assert(s.flags[f],f);assert.equal(s.slots.length,4);});
test('every route state can save, restore and continue to the same ending',()=>{for(let split=0;split<route.length;split++){const s=restore(JSON.stringify(play(route.slice(0,split))));assert.deepEqual(play(route.slice(split),s),play());}});
test('UI-independent source state does not mutate its predecessor',()=>{const a=initialState(),copy=structuredClone(a);dispatch(a,{type:'start'});assert.deepEqual(a,copy);});
test('no stealing locked props or skipping room gates',()=>{let s=play([['start'],['move','server']]);assert.equal(s.room,'newsroom');s=play([['move','archive'],['act','take','firefox']],s);assert(!s.inventory.includes('firefox'));s=dispatch(s,{type:'act',verb:'use',item:'publish',target:'migration'}).state;assert(!s.flags.core);});
test('wrong answers and combinations preserve items and progression',()=>{let s=before(['choose','steel']);const inv=[...s.inventory];s=play([['choose','saturn'],['choose','steel'],['choose','steel']],s);assert.equal(s.progress.career,1);assert.deepEqual(s.inventory,inv);const r=dispatch(s,{type:'combine',a:'portable',b:'coil'});assert.deepEqual(r.state.inventory,inv);assert.match(r.message,/Klebeband/);});
test('all pairs of carried items are safe and never remove unique fragments',()=>{const s=before(['move','server']);for(const a of s.inventory)for(const b of s.inventory){const n=dispatch(s,{type:'combine',a,b}).state;invariants(n);for(const f of FRAGMENTS)assert(n.inventory.includes(f));}});
test('both documented dates are accepted',()=>{const s=before(['choose','4']);for(const id of ['4','5']){const n=dispatch(s,{type:'choose',id}).state;assert(n.flags.origin);assert(n.inventory.includes('origin'));}});
test('each colleague is necessary for their branch',()=>{let s=before(['use','firmware','bridge']);s.flags.felix=false;assert(!play([['use','firmware','bridge']],s).pending);s=before(['use','powered','benny']);s.flags.benny=false;assert(!play([['use','powered','benny']],s).flags.found);assert(!before(['act','talk','andre']).inventory.includes('coil'));assert(!before(['act','talk','olli']).inventory.includes('watch'));});
test('branch order is flexible: laboratory and harbour before workshop',()=>{const split=i=>route.findIndex(x=>JSON.stringify(x)===JSON.stringify(i));const schoolEnd=split(['move','workshop']),lab=split(['move','lab']),quay=split(['move','quay']),server=split(['move','server']);const reordered=[...route.slice(0,schoolEnd),...route.slice(lab,quay),...route.slice(quay,server),...route.slice(schoolEnd,lab),...route.slice(server)];assert.equal(play(reordered).ending,'good');});
test('repeat conversations do not duplicate or regenerate consumed quest equipment',()=>{let s=before(['move','quay']);for(let i=0;i<5;i++)s=play([['act','talk','olli'],['choose','help']],s);assert(!s.inventory.includes('watch'));assert.equal(s.inventory.filter(i=>i==='battery').length,1);s=before(['move','lab']);s=play([['act','talk','andre'],['choose','help']],s);assert(!s.inventory.includes('coil'));});
test('taken props disappear and ghost removal changes the authoritative scene',()=>{const s=play([['start'],['act','take','usb']]);assert(!objects(s).some(o=>o.id==='usb'));const w=before(['act','take','pencil']);assert(!objects(w).some(o=>o.id==='ghost'));assert(objects(w).some(o=>o.id==='pencil'));});
test('clickbait endings are recoverable without losing puzzle progress',()=>{for(const id of ['bait','vague']){let s=before(['choose','clear']);s=play([['choose',id]],s);assert.equal(s.ending,'bad');assert(!s.flags.won);s=play([['continue'],['act','use','headline'],['choose','clear']],s);assert.equal(s.ending,'good');assert.equal(s.slots.length,4);}});
test('hint stages stop at three and reset for new objective',()=>{let s=play([['start']]);const key=objective(s)[0];for(let i=0;i<5;i++)s=play([['hint']],s);assert.equal(s.hintStep,2);assert.equal(s.hintKey,key);s=play([['move','archive'],['act','use','forum'],['choose','kaschi'],['hint']],s);assert.equal(s.hintStep,1);assert.notEqual(s.hintKey,key);});
test('invalid save data is rejected without throwing',()=>{for(const raw of ['',null,'{',{}, {...initialState(),version:999},{...initialState(),inventory:['not-an-item']},{...initialState(),slots:['fake']},{...initialState(),turn:-1},{...initialState(),pending:'unknown'}])assert.equal(restore(raw),null);});
test('all hotspots have unique IDs, descriptions and safe geometry',()=>{assert(HOTSPOT_COUNT>=40);const ids=[];for(const r of Object.values(ROOMS))for(const o of r.objects){assert(o.look.length>30);assert(o.x>=0&&o.y>=0&&o.x+o.w<=100&&o.y+o.h<=100);ids.push(o.id);}assert.equal(new Set(ids).size,ids.length);});
